collections:
  intern-years:
    output: true
    permalink: "/about/interns/year:name/"
defaults:
  - scope:
      type: "intern-years"
    values:
      layout: "intern-year"
exclude:
  - "exclude"
plugins:
  - "jekyll-redirect-from"
whitelist:
  - "jekyll-redirect-from"
